# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Carbon < Formula
  desc "Build tool for custom configuration of multiple smaller services, and wrapper commands for docker containers to make your life easier."
  homepage "https://github.com/0x20F/homebrew-carbon"
  version "1.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/0x20F/carbon/releases/download/v1.1.1/carbon_1.1.1_Darwin_x86_64.tar.gz"
      sha256 "19129915175bc844d4e06ae70de97e8d48787eb89b36f580d5755655fff007a0"

      def install
        bin.install "carbon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/0x20F/carbon/releases/download/v1.1.1/carbon_1.1.1_Darwin_arm64.tar.gz"
      sha256 "c545a765fbe2202f46e037d0cd8f5b699efcb6418d7e8acfdb570f7a60322bce"

      def install
        bin.install "carbon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/0x20F/carbon/releases/download/v1.1.1/carbon_1.1.1_Linux_arm64.tar.gz"
      sha256 "8eac879cbd0e39d07b5f9dc5b34808603a1bcf33415f65ba165da1ac20daf40e"

      def install
        bin.install "carbon"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/0x20F/carbon/releases/download/v1.1.1/carbon_1.1.1_Linux_x86_64.tar.gz"
      sha256 "274e7dca207a149bf342db0b7442e0016732f585c484003b05dc215250b844e1"

      def install
        bin.install "carbon"
      end
    end
  end
end
